// Redir admin - kort. IIFE => ingen globale navn.
(()=>{const sb=supabase.createClient(SUPABASE.url,SUPABASE.publishableKey),$=id=>document.getElementById(id),ready=!SUPABASE.url.includes('YOUR-'),list=$('t').tBodies[0]
$('status').innerHTML=ready?`✅ ${SUPABASE.url}`:'⚠️ Konfigurer <b>db.js</b> (URL + publishable key) – se «Oppsett» under.'
const load=async()=>{const{data,error}=await sb.from('redir').select('id,url,"desc"').order('id');$('msg').textContent=error?.message||'';list.innerHTML=(data||[]).map(r=>`<tr data-id="${r.id}" data-url="${r.url}" data-desc="${r.desc||''}"><td>${r.id}</td><td><a target=_blank rel=noopener href="${r.url}">${r.url}</a></td><td>${r.desc||''}</td><td><button data-e>✎</button><button data-d>🗑</button></td></tr>`).join('')}
$('t').onclick=e=>{const tr=e.target.closest('tr'),b=e.target.closest('button');if(!tr||!b)return;b.hasAttribute('data-e')?($('id').value=tr.dataset.id,$('url').value=tr.dataset.url,$('desc').value=tr.dataset.desc,$('id').dataset.o=tr.dataset.id):b.hasAttribute('data-d')&&confirm(`Slett ${tr.dataset.id}?`)&&sb.from('redir').delete().eq('id',tr.dataset.id).then(load)}
$('f').onsubmit=e=>{e.preventDefault();if(!ready)return $('status').innerHTML='⚠️ Fyll inn <b>db.js</b> først';const id=$('id').value,u=$('url').value,d=$('desc').value,o=$('id').dataset.o||'';(async()=>{if(o&&o!==id)await sb.from('redir').delete().eq('id',o);const{error}=await(o&&o===id?sb.from('redir').update({url:u,desc:d}).eq('id',id):sb.from('redir').insert({id,url:u,desc:d}));$('msg').textContent=error?.message||'';if(!error){$('f').reset();$('id').dataset.o='';load()}})()}
const q=new URLSearchParams(location.search).get('add'),todo=q?(()=>{try{return Object.entries(JSON.parse(q))}catch(e){return []}})():[]
if(todo.length)(async()=>{let n=0,err='';for(const[id,url]of todo){const{error}=await sb.from('redir').upsert({id,url},{onConflict:'id'});error?err=error.message:n++}history.replaceState({},'',location.pathname);await load();$('msg').textContent=err||`La til/oppdaterte ${n} sanger`})()
else ready&&load()})()
